# ==============================================================================
# DATA CONTRACT: INEI - ENAHO
# Capa: Bronze -> Silver
# Motor de Validación Esperado: DuckDB (vía Dagster)
# ==============================================================================
dataset:
  domain: civic
  silver_name: enaho_civic_hhold_base
  grain: hhold
  description: Flags de participación ciudadana por hogar.
  source_system: inei_microdatos
  bronze_name: inei_2023_enaho01_800a_raw
  raw_file_name: Enaho01-2023-800A.csv
  year: 2023
schema:
  physical_type: parquet
  engine: duckdb
  columns:
  - name: AÑO
    type: VARCHAR
    description: Año de la Encuesta
    aliases:
    - ANO
    - ANIO
  - name: MES
    type: VARCHAR
    description: Mes de Ejecución de la Encuesta
  - name: NCONGLOME
    type: VARCHAR
    description: Número de Conglomerado (proveniente del marco)
  - name: SUB_CONGLOME
    type: VARCHAR
    description: Número de Subconglomerado (proveniente del marco)
  - name: CONGLOME
    type: VARCHAR
    description: Número de Conglomerado
  - name: VIVIENDA
    type: VARCHAR
    description: Número de Selección de Vivienda
  - name: HOGAR
    type: VARCHAR
    description: Número secuencial del Hogar
  - name: UBIGEO
    type: VARCHAR
    description: Ubicación geográfica
  - name: DOMINIO
    type: INTEGER
    description: Dominio Geográfico
    semantic_dictionary:
      '1': Costa Norte
      '2': Costa Centro
      '3': Costa Sur
      '4': Sierra Norte
      '5': Sierra Centro
      '6': Sierra Sur
      '7': Selva
      '8': Lima Metropolitana  – 8
    constraints:
    - allowed_values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
  - name: ESTRATO
    type: INTEGER
    description: Estrato Geográfico
    semantic_dictionary:
      '1': De 500 000 a más habitantes
      '2': De 100 000 a 499 999 habitantes
      '3': De 50 000 a 99 999 habitantes
      '4': De 20 000 a 49 999 habitantes
      '5': De 2 000 a 19 999 habitantes
      '6': De 500 a 1 999 habitantes
      '7': Área de Empadronamiento Rural (AER) Compuesto
      '8': Área de Empadronamiento Rural (AER) Simple  – 8
    constraints:
    - allowed_values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
  - name: CODINFOR
    type: VARCHAR
    description: Código de informante del Capítulo 800
  - name: P801_1
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Clubes y asociaciones deportivas?'
    semantic_dictionary:
      '1': Clubes y asociaciones deportivas
    constraints:
    - allowed_values:
      - 1
  - name: P801_2
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Agrupación o partido político?'
    semantic_dictionary:
      '2': Agrupación o partido político
    constraints:
    - allowed_values:
      - 2
  - name: P801_3
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Clubes culturales (danza, música, etc.)?'
    semantic_dictionary:
      '3': Clubes culturales (danza, música, etc.)
    constraints:
    - allowed_values:
      - 3
  - name: P801_4
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Asociación Vecinal / Junta vecinal?'
    semantic_dictionary:
      '4': Asociación vecinal / Junta vecinal
    constraints:
    - allowed_values:
      - 4
  - name: P801_5
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Ronda campesina?'
    semantic_dictionary:
      '5': Ronda campesina
    constraints:
    - allowed_values:
      - 5
  - name: P801_6
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Asociación de regantes?'
    semantic_dictionary:
      '6': Asociación de regantes
    constraints:
    - allowed_values:
      - 6
  - name: P801_7
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Asociación profesional?'
    semantic_dictionary:
      '7': Asociación profesional
    constraints:
    - allowed_values:
      - 7
  - name: P801_8
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Asociación de trabajadores o sindicato?'
    semantic_dictionary:
      '8': Asociación de trabajadores o sindicato
    constraints:
    - allowed_values:
      - 8
  - name: P801_9
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Club de madres?'
    semantic_dictionary:
      '9': Club de madres
    constraints:
    - allowed_values:
      - 9
  - name: P801_10
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Asociación de padres de familia (APAFA)?'
    semantic_dictionary:
      '10': Asociación de padres de familia (APAFA)
    constraints:
    - allowed_values:
      - 10
  - name: P801_11
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Vaso de leche?'
  - name: P801_12
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Comedor popular?'
    semantic_dictionary:
      '12': Comedor popular
    constraints:
    - allowed_values:
      - 12
  - name: P801_13
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Comité local administrativo de salud (CLAS)?'
    semantic_dictionary:
      '13': Comité local administrativo de salud (CLAS)
    constraints:
    - allowed_values:
      - 13
  - name: P801_14
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Proceso de presupuesto participativo?'
    semantic_dictionary:
      '14': Proceso de presupuesto participativo
    constraints:
    - allowed_values:
      - 14
  - name: P801_15
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Concejo de coordinación local distrital
      (CCLD)?'
    semantic_dictionary:
      '15': Concejo de coordinación local distrital
    constraints:
    - allowed_values:
      - 15
  - name: P801_16
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Comunidad campesina?'
    semantic_dictionary:
      '16': Comunidad campesina
    constraints:
    - allowed_values:
      - 16
  - name: P801_17
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Asociación agropecuaria?'
    semantic_dictionary:
      '17': Asociación agropecuaria
    constraints:
    - allowed_values:
      - 17
  - name: P801_18
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Otro/a?'
    semantic_dictionary:
      '18': Otro/a
    constraints:
    - allowed_values:
      - 18
  - name: P801_19
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: No pertenece, no participa?'
    semantic_dictionary:
      '19': No pertenece, no participa
    constraints:
    - allowed_values:
      - 19
  - name: P801_20
    type: INTEGER
    description: '¿Usted o algún miembro de su hogar pertenece o participa en algún
      grupo, organización y/o asociación: Participación en la preparación de desayuno
      y/o almuerzo escolar?'
    semantic_dictionary:
      '20': Participación en la preparación de desayuno y/o almuerzo escolar
    constraints:
    - allowed_values:
      - 20
  - name: P806
    type: INTEGER
    description: ¿Por qué no han participado?
    semantic_dictionary:
      '1': No sabía que había algún proceso de elección
      '2': No tiene conocidos
      '3': No conoce personas influyentes
      '4': No es miembro del partido
      '5': No le interesa
      '6': No cree
      '7': Falta de tiempo
      '8': Otra razón Rngo 1-8
    constraints:
    - allowed_values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
  - name: TICUEST01
    type: INTEGER
    description: Origen de cuestionario
    semantic_dictionary:
      '1': Cuestionario en hojas
      '2': Cuestionario en Tablet
    constraints:
    - allowed_values:
      - 1
      - 2
  - name: FACTOR07
    type: DOUBLE
    description: Factor de expansión anual proyecciones CPV-2007
