# ==============================================================================
# DATA CONTRACT: INEI - ENAHO
# Capa: Bronze -> Silver
# Motor de Validación Esperado: DuckDB (vía Dagster)
# ==============================================================================
dataset:
  domain: food_expenses
  silver_name: enaho_food_expenses_hhold_charity_reasons
  grain: hhold
  description: Motivos para acudir a instituciones benéficas.
  source_system: inei_microdatos
  bronze_name: inei_2023_enaho01_602b_raw
  raw_file_name: Enaho01-2023-602B.csv
  year: 2023
schema:
  physical_type: parquet
  engine: duckdb
  columns:
  - name: AÑO
    type: VARCHAR
    description: Año de la Encuesta
    aliases:
    - ANO
    - ANIO
  - name: MES
    type: VARCHAR
    description: Mes de Ejecución de la Encuesta
  - name: NCONGLOME
    type: VARCHAR
    description: Número de Conglomerado (proveniente del marco)
  - name: SUB_CONGLOME
    type: VARCHAR
    description: Número de Subconglomerado (proveniente del marco)
  - name: CONGLOME
    type: VARCHAR
    description: Número de Conglomerado
  - name: VIVIENDA
    type: VARCHAR
    description: Número de Selección de Vivienda
  - name: HOGAR
    type: VARCHAR
    description: Número secuencial del Hogar
  - name: UBIGEO
    type: VARCHAR
    description: Ubicación geográfica
  - name: DOMINIO
    type: INTEGER
    description: Dominio Geográfico
    semantic_dictionary:
      '1': Costa Norte
      '2': Costa Centro
      '3': Costa Sur
      '4': Sierra Norte
      '5': Sierra Centro
      '6': Sierra Sur
      '7': Selva
      '8': Lima Metropolitana  – 8
    constraints:
    - allowed_values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
  - name: ESTRATO
    type: INTEGER
    description: Estrato Geográfico
    semantic_dictionary:
      '1': De 500 000 a más habitantes
      '2': De 100 000 a 499 999 habitantes
      '3': De 50 000 a 99 999 habitantes
      '4': De 20 000 a 49 999 habitantes
      '5': De 2 000 a 19 999 habitantes
      '6': De 500 a 1 999 habitantes
      '7': Área de Empadronamiento Rural (AER) Compuesto
      '8': Área de Empadronamiento Rural (AER) Simple  – 8 P602OC 100 0 C ¿Cuál es
        el nombre de la olla común del cual obtiene/obtuvo los alimentos?
    constraints:
    - allowed_values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
  - name: P602E91
    type: INTEGER
    description: ¿Cuál es la razón por la que su hogar recibe o recibió alimentos
      de la olla común? - No tengo/tenía trabajo
    semantic_dictionary:
      '0': Pase
      '1': No tengo/tenía trabajo  ,1
    constraints:
    - allowed_values:
      - 0
      - 1
  - name: P602E92
    type: INTEGER
    description: ¿Cuál es la razón por la que su hogar recibe o recibió alimentos
      de la olla común? - Sus ingresos no le alcanzan/alcanzaba
    semantic_dictionary:
      '0': Pase
      '2': Sus ingresos no le alcanzan/alcanzaba  ,2
    constraints:
    - allowed_values:
      - 0
      - 2
  - name: P602E93
    type: INTEGER
    description: ¿Cuál es la razón por la que su hogar recibe o recibió alimentos
      de la olla común? - Venden/Vendían a precio económico
    semantic_dictionary:
      '0': Pase
      '3': Venden/Vendían a precio económico  ,3
    constraints:
    - allowed_values:
      - 0
      - 3
  - name: P602E94
    type: INTEGER
    description: ¿Cuál es la razón por la que su hogar recibe o recibió alimentos
      de la olla común? - Por falta de tiempo para cocinar
    semantic_dictionary:
      '0': Pase
      '4': Por falta de tiempo para cocinar  ,4
    constraints:
    - allowed_values:
      - 0
      - 4
  - name: P602E95
    type: INTEGER
    description: ¿Cuál es la razón por la que su hogar recibe o recibió alimentos
      de la olla común? - Otra razón(Especifique)
    semantic_dictionary:
      '0': Pase
      '5': Otra razón(Especifique)  ,5
    constraints:
    - allowed_values:
      - 0
      - 5
  - name: TICUEST01
    type: INTEGER
    description: Origen de cuestionario
    semantic_dictionary:
      '1': Cuestionario en hojas
      '2': Cuestionario en Tablet
    constraints:
    - allowed_values:
      - 1
      - 2
  - name: FACTOR07
    type: DOUBLE
    description: Factor de expansión anual proyecciones CPV-2007
