# ==============================================================================
# DATA CONTRACT: INEI - ENAHO
# Capa: Bronze -> Silver
# Motor de Validación Esperado: DuckDB (vía Dagster)
# ==============================================================================
dataset:
  domain: food_expenses
  silver_name: enaho_food_expenses_item_kids_out
  grain: item
  description: Alimentos fuera del hogar para < 14 años.
  source_system: inei_microdatos
  bronze_name: inei_2023_enaho01_602a_raw
  raw_file_name: Enaho01-2023-602A.csv
  year: 2023
schema:
  physical_type: parquet
  engine: duckdb
  columns:
  - name: AÑO
    type: VARCHAR
    description: Año de la Encuesta
    aliases:
    - ANO
    - ANIO
  - name: MES
    type: VARCHAR
    description: Mes de Ejecución de la Encuesta
  - name: NCONGLOME
    type: VARCHAR
    description: Número de Conglomerado (proveniente del marco)
  - name: SUB_CONGLOME
    type: VARCHAR
    description: Número de Subconglomerado (proveniente del marco)
  - name: CONGLOME
    type: VARCHAR
    description: Número de Conglomerado
  - name: VIVIENDA
    type: VARCHAR
    description: Número de Selección de Vivienda
  - name: HOGAR
    type: VARCHAR
    description: Número secuencial del Hogar
  - name: UBIGEO
    type: VARCHAR
    description: Ubicación geográfica
  - name: DOMINIO
    type: INTEGER
    description: Dominio Geográfico
    semantic_dictionary:
      '1': Costa Norte
      '2': Costa Centro
      '3': Costa Sur
      '4': Sierra Norte
      '5': Sierra Centro
      '6': Sierra Sur
      '7': Selva
      '8': Lima Metropolitana  – 8
    constraints:
    - allowed_values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
  - name: ESTRATO
    type: INTEGER
    description: Estrato Geográfico
    semantic_dictionary:
      '1': De 500 000 a más habitantes
      '2': De 100 000 a 499 999 habitantes
      '3': De 50 000 a 99 999 habitantes
      '4': De 20 000 a 49 999 habitantes
      '5': De 2 000 a 19 999 habitantes
      '6': De 500 a 1 999 habitantes
      '7': Área de Empadronamiento Rural (AER) Compuesto
      '8': Área de Empadronamiento Rural (AER) Simple RAlaimngeon t:o 1s –c o8nsumidos
        fuera del hogar obtenidos por instituciones benéficas (Para
    constraints:
    - allowed_values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
  - name: P602N1
    type: INTEGER
    description: menores de 14 años)
    semantic_dictionary:
      '1': Desayuno Escolar
      '2': Almuerzo Escolar
      '3': Otros (Especifique)
      '4': Otros (Especifique)
      '5': Otros (Especifique)
    constraints:
    - allowed_values:
      - 1
      - 2
      - 3
      - 4
      - 5
  - name: P6021
    type: INTEGER
    description: ¿En los últimos 15 días, algún miembro de este hogar obtuvieron,
      compraron o le regalaron alimentos para consumir fuera del hogar de:?
    semantic_dictionary:
      '1': Si
      '2': No    – 2
    sentinel_nulls:
    - 9
    constraints:
    - allowed_values:
      - 1
      - 2
  - name: P602A1
    type: INTEGER
    description: Generalmente, ¿Cuántas veces por semana?
    sentinel_nulls:
    - 99
  - name: P602B1
    type: INTEGER
    description: Generalmente, ¿Cuántas raciones recibieron cada vez?
    sentinel_nulls:
    - 99
  - name: P602C1
    type: INTEGER
    description: Generalmente, ¿Cuántos miembros de su hogar consumieron cada vez?
    sentinel_nulls:
    - 99
  - name: P602D1A
    type: INTEGER
    description: '¿Pagó: por el alimento?'
    semantic_dictionary:
      '0': Pase
      '1': Pagó por el alimento  ,1
    constraints:
    - allowed_values:
      - 0
      - 1
  - name: P602D1B
    type: INTEGER
    description: '¿Pagó: por otros pagos asociados (Transporte del alimento, kerosene,
      cocinera,etc)'
    semantic_dictionary:
      '0': Pase
      '2': Pagó por otros pagos asociados(transporte del alimento, combustible, cocinera,
        etc)  ,2
    constraints:
    - allowed_values:
      - 0
      - 2
  - name: P602D1C
    type: INTEGER
    description: No realizo ningun pago
    semantic_dictionary:
      '0': Pase
      '3': No realizó ningún pago
    constraints:
    - allowed_values:
      - 0
      - 3
  - name: P602E3
    type: DOUBLE
    description: ¿Cuánto pagó cada vez por el alimento recibido? 999999.
    sentinel_nulls:
    - '9'
  - name: P602E4
    type: DOUBLE
    description: ¿Cuánto pagó en el mes anterior por otros conceptos? 999999.
    sentinel_nulls:
    - '9'
  - name: D602E3
    type: DOUBLE
    description: (Deflactado, anualizado) ¿Cuánto pagó cada vez por el alimento recibido?
      999999.
    sentinel_nulls:
    - '9'
  - name: D602E4
    type: DOUBLE
    description: (Deflactado, anualizado) ¿Cuánto pagó en el mes anterior por otros
      conceptos? 999999.
    sentinel_nulls:
    - '9'
  - name: I602E3
    type: DOUBLE
    description: (Imputado, deflactado, anualizado) ¿Cuánto pagó cada vez por el alimento
      recibido?
  - name: I602E4
    type: DOUBLE
    description: (Imputado, deflactado, anualizado) ¿Cuánto pagó en el mes anterior
      por otros conceptos?
  - name: TICUEST01
    type: INTEGER
    description: Origen de cuestionario
    semantic_dictionary:
      '1': Cuestionario en hojas
      '2': Cuestionario en Tablet
    constraints:
    - allowed_values:
      - 1
      - 2
  - name: FACTOR07
    type: DOUBLE
    description: Factor de expansión anual proyecciones CPV-2007
